import http from 'node:http';
import {PURCHASE_MESSAGE,TELEGRAM_URL} from './public/storefront.js';
import {DatabaseSync} from 'node:sqlite';
import {randomBytes,scryptSync,timingSafeEqual,createHmac} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
const designCatalog=JSON.parse(fs.readFileSync(new URL('./public/designs/catalog.json',import.meta.url),'utf8'));
const db=new DatabaseSync(process.env.DB_PATH||'data/store.db');
db.exec(`PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,name TEXT,email TEXT UNIQUE,password TEXT,role TEXT); CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id INTEGER REFERENCES users(id),expires INTEGER); CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY,name TEXT UNIQUE); CREATE TABLE IF NOT EXISTS templates(id INTEGER PRIMARY KEY,name TEXT,category TEXT,description TEXT,price INTEGER CHECK(price>=0 AND price<=2000000),technology TEXT,designer TEXT,status TEXT,style INTEGER,seller_id INTEGER REFERENCES users(id)); CREATE TABLE IF NOT EXISTS cart(user_id INTEGER,template_id INTEGER,UNIQUE(user_id,template_id)); CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY,user_id INTEGER REFERENCES users(id),total INTEGER,status TEXT,created TEXT,authority TEXT UNIQUE); CREATE TABLE IF NOT EXISTS order_items(order_id INTEGER REFERENCES orders(id),template_id INTEGER REFERENCES templates(id),price INTEGER,UNIQUE(order_id,template_id)); CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY,order_id INTEGER UNIQUE REFERENCES orders(id),reference TEXT UNIQUE,status TEXT); CREATE TABLE IF NOT EXISTS files(id INTEGER PRIMARY KEY,template_id INTEGER,path TEXT,original_name TEXT); CREATE TABLE IF NOT EXISTS reviews(id INTEGER PRIMARY KEY,user_id INTEGER,template_id INTEGER,rating INTEGER CHECK(rating BETWEEN 1 AND 5),body TEXT,UNIQUE(user_id,template_id)); CREATE TABLE IF NOT EXISTS settlements(id INTEGER PRIMARY KEY,seller_id INTEGER,amount INTEGER,status TEXT); CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY,user_id INTEGER,action TEXT,created TEXT);`);
const categories=['فروشگاهی','شرکتی','شخصی','خبری','وبلاگ','آشپزی','آموزشی','هوش مصنوعی','نمونه‌کار','پزشکی','خدماتی','صفحه فرود'];
const names=[['آرا | فروشگاه دکوراسیون','نووا | پوشاک مینیمال','چرمین | محصولات چرمی','دیجینو | کالای دیجیتال','گلدیس | گل و گیاه','زیور | جواهرات'],['آرک | معماری مدرن','مدار | شرکت فناوری','سازه | مهندسی عمران','فراز | مشاوره کسب‌وکار','مانا | انرژی پایدار','رهام | حمل و نقل'],['رها | وب‌سایت نویسنده','آوا | صفحه موسیقی','سفرنامه | جهانگردی','نیک | مربی شخصی','سایه | هنرمند','روایت | رزومه حرفه‌ای'],['دیدبان | مجله خبری','میدان | اخبار ورزشی','فردا | فناوری روز','قاب | اخبار سینما','شهر | خبر محلی','سرمایه | تحلیل بازار'],['کاغذ | یادداشت روزانه','کوچ | وبلاگ سفر','سبز | زندگی پایدار','واژه | نقد کتاب','مسیر | تجربه‌های کاری','لنز | مجله عکاسی'],['زعفران | رستوران ایرانی','بُن | کافه تخصصی','مزه | دستور آشپزی','تنور | نانوایی','ریحان | غذای سالم','شیرین | قنادی'],['دانش | آموزش آنلاین','زبانک | آموزش زبان','کدنما | مدرسه برنامه‌نویسی','بوم | آموزش هنر','مسئله | کلاس ریاضی','مهارت | دوره حرفه‌ای'],['نورون | دستیار هوشمند','پیکسل | تولید تصویر','پرسش | چت هوشمند','آینده | استارتاپ هوش مصنوعی','داده | تحلیل هوشمند','نویسا | دستیار محتوا'],['استودیو | طراحی گرافیک','زاویه | عکاسی معماری','حرکت | موشن گرافیک','هویت | طراحی برند','اثر | گالری هنر','نقطه | طراح محصول'],['آرام | کلینیک روانشناسی','لبخند | دندانپزشکی','تندرست | مرکز پزشکی','مهر | کلینیک کودک','بینش | چشم‌پزشکی','درمان | فیزیوتراپی'],['همیار | خدمات منزل','پاک | خشکشویی','داد | دفتر حقوقی','سرو | باغبانی','راه | آژانس گردشگری','تعمیر | خدمات فنی'],['سپهر | معرفی اپلیکیشن','رشد | کمپین بازاریابی','رویداد | همایش','شروع | محصول دیجیتال','آهنگ | معرفی پادکست','وصل | عضویت خبرنامه']];
if(!db.prepare('SELECT id FROM templates LIMIT 1').get()){categories.forEach((c,i)=>{db.prepare('INSERT INTO categories(name) VALUES(?)').run(c);names[i].forEach((n,j)=>db.prepare('INSERT INTO templates(name,category,description,price,technology,designer,status,style) VALUES(?,?,?,?,?,?,?,?)').run(n,c,`قالب ${n.split(' | ')[1]} با طراحی اختصاصی، صفحات واکنش‌گرا و ساختار مناسب محتوای فارسی. این محصول بخشی از کاتالوگ نمونه است.`,j===5?0:[500000,1000000,1500000,2000000][(i+j)%4],['HTML / CSS','React','Next.js','WordPress'][(i+j)%4],['استودیو آرا','مریم احمدی','علی رضایی','استودیو نقطه'][j%4],'published',i*6+j));});}
export function validPrice(p){return Number.isInteger(p)&&p>=0&&p<=2000000}
export function totalFor(ids){return [...new Set(ids)].map(id=>db.prepare("SELECT * FROM templates WHERE id=? AND status='published'").get(id)).reduce((s,t)=>{if(!t)throw Error('قالب در دسترس نیست');return s+t.price},0)}
const hash=p=>{let salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(p,salt,64).toString('hex')};
const match=(p,h)=>{try{let [s,k]=h.split(':');return timingSafeEqual(scryptSync(p,s,64),Buffer.from(k,'hex'))}catch{return false}};
const sessions=req=>{let token=(req.headers.cookie||'').match(/session=([a-f0-9]+)/)?.[1];return token?db.prepare('SELECT users.id,name,email,role FROM users JOIN sessions ON users.id=sessions.user_id WHERE token=? AND expires>?').get(token,Date.now()):null};
const limit=new Map();
const json=(res,n,data)=>{res.writeHead(n,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data))};
const own=(uid,tid)=>db.prepare("SELECT 1 FROM orders o JOIN order_items i ON i.order_id=o.id WHERE o.user_id=? AND i.template_id=? AND o.status='paid'").get(uid,tid);
async function body(req){let s='';for await(const x of req){s+=x;if(s.length>100000)throw Error('حجم درخواست بیش از حد مجاز است')}return JSON.parse(s||'{}')}
const server=http.createServer(async(req,res)=>{try{
res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','SAMEORIGIN');
let url=new URL(req.url,'http://localhost'),p=url.pathname,u=sessions(req);
if(p.startsWith('/api/')){
res.setHeader('Cache-Control','no-store');
if(req.method!=='GET'&&req.headers.origin&&req.headers.origin!==`http://${req.headers.host}`&&req.headers.origin!==process.env.APP_URL)return json(res,403,{error:'مبدأ درخواست معتبر نیست'});
let b=req.method==='GET'?{}:await body(req);
if(p==='/api/templates'&&req.method==='GET')return json(res,200,{templates:designCatalog.map(design=>{const row=db.prepare("SELECT * FROM templates WHERE id=? AND status='published'").get(design.id);return row?{...row,...design}:null}).filter(Boolean),categories,demo:true});
if(p==='/api/me')return json(res,200,{user:u||null});
if(['/api/register','/api/login','/api/admin/login'].includes(p)){
let key=req.socket.remoteAddress;let entry=limit.get(key)||{count:0,time:Date.now()};if(Date.now()-entry.time>900000)entry={count:0,time:Date.now()};entry.count++;limit.set(key,entry);if(entry.count>15)return json(res,429,{error:'تلاش‌های بیش از حد؛ ۱۵ دقیقه بعد دوباره امتحان کنید.'});
if(p==='/api/register'){if(!b.name||!/^\S+@\S+\.\S+$/.test(b.email)||typeof b.password!=='string'||b.password.length<10)return json(res,400,{error:'نام، ایمیل معتبر و رمز با حداقل ۱۰ نویسه وارد کنید.'});try{db.prepare('INSERT INTO users(name,email,password,role) VALUES(?,?,?,?)').run(b.name,b.email.toLowerCase(),hash(b.password),b.role==='seller'?'seller':'buyer')}catch{return json(res,409,{error:'این ایمیل قبلاً ثبت شده است.'})}}
if(p==='/api/admin/login'){if(!process.env.ADMIN_EMAIL||!process.env.ADMIN_PASSWORD_HASH)return json(res,503,{error:'ورود مدیر هنوز در سرور پیکربندی نشده است.'});if(b.email!==process.env.ADMIN_EMAIL||!match(b.password||'',process.env.ADMIN_PASSWORD_HASH))return json(res,401,{error:'اطلاعات ورود صحیح نیست.'});db.prepare("INSERT INTO users(name,email,password,role) VALUES('مدیر',?,?,'admin') ON CONFLICT(email) DO UPDATE SET role='admin',password=excluded.password").run(b.email,process.env.ADMIN_PASSWORD_HASH)}
let user=db.prepare('SELECT * FROM users WHERE email=?').get(String(b.email).toLowerCase());if(!user||!match(b.password||'',user.password))return json(res,401,{error:'ایمیل یا رمز عبور صحیح نیست.'});let token=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(token,user.id,Date.now()+86400000);res.setHeader('Set-Cookie',`session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=86400${process.env.NODE_ENV==='production'?'; Secure':''}`);return json(res,200,{ok:true});}
if(p==='/api/logout'){db.prepare('DELETE FROM sessions WHERE token=?').run((req.headers.cookie||'').match(/session=([a-f0-9]+)/)?.[1]||'');res.setHeader('Set-Cookie','session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');return json(res,200,{ok:true})}
if(p==='/api/reset')return json(res,503,{error:'ارسال ایمیل بازیابی هنوز پیکربندی نشده است؛ با پشتیبانی تماس بگیرید.'});
if(p==='/api/checkout')return json(res,503,{error:PURCHASE_MESSAGE,telegram:TELEGRAM_URL,paymentAvailable:false});
if(!u)return json(res,401,{error:'ابتدا وارد حساب کاربری شوید.'});
if(p==='/api/orders')return json(res,200,db.prepare('SELECT * FROM orders WHERE user_id=? ORDER BY id DESC').all(u.id));
if(p==='/api/payment/callback')return json(res,503,{error:'درگاه پیکربندی نشده است. سفارش تأیید نمی‌شود.'});
if(p==='/api/reviews'){if(!own(u.id,b.template_id))return json(res,403,{error:'دیدگاه فقط برای خریدار تأییدشده فعال است.'});if(!Number.isInteger(b.rating)||b.rating<1||b.rating>5)return json(res,400,{error:'امتیاز باید بین ۱ تا ۵ باشد.'});db.prepare('INSERT INTO reviews(user_id,template_id,rating,body) VALUES(?,?,?,?)').run(u.id,b.template_id,b.rating,String(b.body).slice(0,2000));return json(res,200,{ok:true})}
if(p==='/api/download')return json(res,403,{error:'فایل قابل دانلودی برای سفارش تأییدشده در دسترس نیست.'});
if(p.startsWith('/api/seller')){if(!['seller','admin'].includes(u.role))return json(res,403,{error:'این بخش مخصوص فروشندگان است.'});if(p==='/api/seller/templates'&&req.method==='GET')return json(res,200,db.prepare('SELECT * FROM templates WHERE seller_id=?').all(u.id));if(p==='/api/seller/templates'&&req.method==='POST'){if(!b.name||!categories.includes(b.category)||!validPrice(b.price))return json(res,400,{error:'نام، دسته‌بندی و قیمت صحیح (حداکثر ۲٬۰۰۰٬۰۰۰ تومان) الزامی است.'});db.prepare("INSERT INTO templates(name,category,description,price,technology,designer,status,style,seller_id) VALUES(?,?,?,?,?,?,'pending',0,?)").run(b.name,b.category,b.description||'',b.price,b.technology||'HTML / CSS',u.name,u.id);return json(res,200,{ok:true})}return json(res,503,{error:'نگهداری امن فایل و تسویه هنوز پیکربندی نشده است.'})}
if(p.startsWith('/api/admin')){if(u.role!=='admin')return json(res,403,{error:'دسترسی فقط برای مدیر مجاز است.'});if(req.method==='GET')return json(res,200,{templates:db.prepare('SELECT * FROM templates').all(),orders:db.prepare('SELECT * FROM orders').all(),users:db.prepare('SELECT id,name,email,role FROM users').all(),audit:db.prepare('SELECT * FROM audit ORDER BY id DESC').all()});if(!['published','rejected','disabled'].includes(b.status))return json(res,400,{error:'وضعیت معتبر نیست.'});db.prepare('UPDATE templates SET status=? WHERE id=?').run(b.status,b.id);db.prepare('INSERT INTO audit(user_id,action,created) VALUES(?,?,?)').run(u.id,`template ${b.id}: ${b.status}`,new Date().toISOString());return json(res,200,{ok:true})}
return json(res,404,{error:'مسیر یافت نشد.'});}
let file=p==='/'?'public/index.html':path.join('public',p);if(!path.resolve(file).startsWith(path.resolve('public')+path.sep))return res.end();if(!fs.existsSync(file)||fs.statSync(file).isDirectory())file='public/index.html';res.setHeader('Content-Type',file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.json')?'application/json':'text/html; charset=utf-8');if(p.startsWith('/designs/'))res.setHeader('Content-Security-Policy',"sandbox; default-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self'; base-uri 'none'; form-action 'none'");res.end(fs.readFileSync(file));
}catch(e){json(res,400,{error:e.message||'خطایی رخ داد. دوباره تلاش کنید.'})}});
if(process.env.NODE_ENV!=='test')server.listen(Number(process.env.PORT||3000),'0.0.0.0',()=>console.log('Persian Dark Horse running at http://localhost:3000'));
export {server,db,hash,match};
